version: "3.8"

services:
  go_auth_db:
    image: postgres:latest
    container_name: go_auth_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  go_auth_app:
    build: .
    volumes:
      - .:/app
    container_name: go_auth_app
    restart: always
    depends_on:
      - go_auth_db
    environment:
      - DB_HOST= ${POSTGRES_HOST}
      - DB_USER= ${POSTGRES_USER}
      - DB_PASSWORD= ${POSTGRES_PASSWORD}
      - DB_NAME= ${POSTGRES_DATABASE}
      - DB_PORT= ${POSTGRES_PORT}
    env_file:
      - .env
    ports:
      - "8080:8080"

volumes:
  postgres_data:
